name: JustWatched

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      BACK_ENV: ${{ vars.BACK_ENV }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prune Docker, Build and Run with Docker Compose
        run: |
          docker system prune -f
          echo "$BACK_ENV" > ./justwatched-backend/.env
          echo "📦 BACK_ENV:"
          cat ./justwatched-backend/.env  
          docker compose down
          docker compose up -f ./justwatched-backend/docker-compose.production.yml -d --build
